In [2]:
import os
from pathlib import Path

print(os.getcwd())
raw_data_path = Path("/Volumes/SANDISKUSBC/MLOps/hdb_price_prediction_mlops/data/raw")
os.listdir(raw_data_path)

/Volumes/SANDISKUSBC/MLOps/hdb_price_prediction_mlops/notebooks

['clean_eval.csv',
 'hdb_resale_index.csv',
 'hold.csv',
 'hdb_resale_flat_transactions.csv',
 'train.csv',
 'clean_train.csv',
 'eval.csv']

In [32]:
import json
import pandas as pd
from urllib.request import Request, urlopen

hdr = {'User-Agent': 'Mozilla/5.0', "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8"}
url = "https://tablebuilder.singstat.gov.sg/api/table/tabledata/M212161?isTestApi=true"

# Fetch the data
request = Request(url, headers=hdr)
data_bytes = urlopen(request).read()

# Parse the bytes data into a JSON dictionary
json_data = json.loads(data_bytes.decode('utf-8'))

# Safely extract the 'row' list
records = json_data.get('Data', {}).get('row', [])

if records:
    # Fetch the 'columns' data from the very first record
    columns_data = records[0].get('columns', [])
    
    # Let's print the first 5 records to verify
    print("First 5 records from 'columns':")
    print(json.dumps(columns_data[:5], indent=4))
    
    # Optional: Convert it cleanly into a Pandas DataFrame!
    # Rename 'key' to 'Quarter' and 'value' to 'Resale_Price_Index'
    df = pd.DataFrame(columns_data).rename(columns={'key': 'quarter', 'value': 'resale_price_index'})
    
    # Convert the value column to float (it comes in as a string initially)
    df['resale_price_index'] = pd.to_numeric(df['resale_price_index'], errors='coerce')
    
    print("\nDataFrame Output:")
    display(df.head())
else:
    print("No records found in the data.")

First 5 records from 'columns':
[
    {
        "key": "1990 1Q",
        "value": "24.3"
    },
    {
        "key": "1990 2Q",
        "value": "24.4"
    },
    {
        "key": "1990 3Q",
        "value": "25"
    },
    {
        "key": "1990 4Q",
        "value": "24.7"
    },
    {
        "key": "1991 1Q",
        "value": "24.9"
    }
]

DataFrame Output:

   quarter  resale_price_index
0  1990 1Q                24.3
1  1990 2Q                24.4
2  1990 3Q                25.0
3  1990 4Q                24.7
4  1991 1Q                24.9

In [33]:
df

     quarter  resale_price_index
0    1990 1Q                24.3
1    1990 2Q                24.4
2    1990 3Q                25.0
3    1990 4Q                24.7
4    1991 1Q                24.9
..       ...                 ...
139  2024 4Q               197.9
140  2025 1Q               201.0
141  2025 2Q               202.9
142  2025 3Q               203.7
143  2025 4Q               203.6

[144 rows x 2 columns]

In [34]:
df.to_csv(raw_data_path/'hdb_resale_index.csv',index=None)
print(f'Successfully save df to csv in {raw_data_path}')

Successfully save df to csv in /Volumes/SANDISKUSBC/MLOps/hdb_price_prediction_mlops/data/raw